### ISSUE TITLE
Firefox: toolbar icon now always has a notification dot under it

### ISSUE THREAD

**Issue by will-stone** [kagisearch/browser_extensions#19]
Hi,

The Firefox Kagi toolbar button has started displaying a dot under it, and says "permission needed" when hovered:

<img width="116" alt="image" src="https://github.com/kagisearch/browser_extensions/assets/654103/13ac9124-23e2-44d5-8a74-dce2d0e0e900">

Clicking it makes the dot go away, but it reappears on navigation.

**Comment by vprelovac** [comment]
We pushed a new version 0.3.3 which should land tomorrow.

**Comment by will-stone** [comment]
Oh, I could have sworn this was 0.3.3 but I’ll check again when I’m back at my computer.

**Comment by hmnd** [comment]
@will-stone "The purpose of them will be to show which MV3 extensions require user to action on them to grant permissions."[^1]

Since the extension has now been updated to use manifest v3, it will show this dot until you click it. Once you click it for a given site, the extension gets permission to the site's URL and is then able to use that to generate a summary. That way it doesn't have access to you full browsing history.

[^1]: [Mozilla Forum](https://discourse.mozilla.org/t/what-are-those-green-dots-under-some-addons-in-new-firefox-developer-edition-107/106797/2)

**Comment by will-stone** [comment]
Thanks @hmnd, so if I read that correctly it means: it is required to click the button on every visited URL to remove the dot. I feel like I’m conditioned to notice when these dots appear, as I associate them with notifications, so I’m not sure that’s an ideal UX. I know adding config is a pain, but any chance of an option to disable the summariser?

**Comment by hmnd** [comment]
@will-stone correct. I find it annoying too, but this behavior is really up to Firefox's devs and not Kagi's. The easiest solution for you would be to hide the addon from your toolbar (right-click extension > uncheck _Pin to Toolbar_).

A possible solution could be to make the `activeTab` permission optional, and request it before showing the summarizer. Depends on what @BrunoBernardino @vprelovac think.

**Comment by BrunoBernardino** [comment]
Indeed I noticed this too, when we switched from `tabs` to `activeTab` (much better permission, the least necessary). I only have `uBlock origin` installed and it has access to everything, so I don't have a good example of another extension with similar restricted permissions to test.

I also can't find anyone mentioning this in https://discourse.mozilla.org/search?q=activetab%20category%3A35%20order%3Alatest

I can try to look into making it optional to try and make that go away.

**Comment by BrunoBernardino** [comment]
Ok, I just experimented with this and even with `activeTab` in `optional_permissions` and only requesting it when you click `Summarize`, the dot in the icon still shows before clicking the extension.

It seems the only solution is to reach out to the Firefox team and tell them that's annoying, and have them make it a preference in `about:config`, at a minimum.

**Comment by hmnd** [comment]
@BrunoBernardino the idea with putting it in `optional_permissions` would be to allow the user to not use summarize at all. Once the `activeTab` permissions is requested+granted, the dot returns. Otherwise, if the user dismisses the prompt to get `activeTab` permissions for summarize, the extension won't have a dot because it can't be activated on any page.

**Comment by BrunoBernardino** [comment]
@hmnd are you certain of that? It wasn't what I experienced with the extension in dev mode, but perhaps it's different outside of it. If so, I can put that in.

**Comment by hmnd** [comment]
@BrunoBernardino did you test with a clean slate? Ie. remove dev+prod extension, reinstall? The permission would still stick from before unless removed.

**Comment by hmnd** [comment]
This is what the right click menu should look like if the extension doesn't have `activeTab` permission:
![image](https://github.com/kagisearch/browser_extensions/assets/12853597/201cbf83-ef3c-4698-a8f1-91c209a3af43)

vs. with:
![image](https://github.com/kagisearch/browser_extensions/assets/12853597/17cf04f7-d6a4-43f6-a9f0-f4c2603f3a34)

**Comment by BrunoBernardino** [comment]
Alright, I didn't reject the permission, and I thought this would make the dot go away even with the permission enabled. I understand that's not the case. I can make that change to optional, so people can use the extension without it (without the summarizer). It seems a bit overkill here since the summarizer is free anyway, though. What do you think, @vprelovac ? Is it worth adding this extra complexity in the code (optional permission handling) to allow people the choice to _not_ share the active tab and thus use the summarizer from the extension?

**Comment by alabhyajindal** [comment]
I am facing this issue and opened a duplicate issue (#38), now closed.

Is this a problem for others as well?

**Comment by BrunoBernardino** [comment]
@alabhyajindal when you're using the summarizer, it's just how Firefox tells you the extension is asking for permissions it doesn't yet have (for that tab in that session). We can't change that without asking for more permissions.

**Comment by alabhyajindal** [comment]
Okay, understood. Thanks! 🙏🏼

**Comment by ilyagr** [comment]
I also stumbled on this (see https://kagifeedback.org/d/2729-firefox-extension-creates-an-annoying-notification-all-the-time/2). As I mentioned there, it seems like a problem to me.

I think a practical workaround would be to use something like https://addons.mozilla.org/en-US/firefox/addon/search-engines-helper/ instead of the Kagi extension.
